---
- name: install netbox on server
  hosts: all

  #tasks:
  #- name: install postgresql repo
  #  command: yum install https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
      
  roles:
    - ANXS.postgresql
    - lae.netbox
    
  vars:
    #netbox_database: netbox
    netbox_database_user: postgres
    #netbox_database_password: changeme
    #netbox_database_host: localhost
    netbox_stable: true
    netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
    netbox_superuser_password: netbox
    netbox_socket: "0.0.0.0:80"
    postgresql_version: 9.6
    postgresql_service_enabled: true
    netbox_config:
      ALLOWED_HOSTS:
        - *
      #MEDIA_ROOT: "{{ netbox_shared_path }}/media"
      REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
    postgresql_users:
      - name: "{{ netbox_database_user }}"
        role_attr_flags: CREATEDB,NOSUPERUSER
